### ISSUE TITLE
Resetting master to be 2.2

### ISSUE THREAD

**Issue by mguijarr** [mxcube/HardwareObjects#16]
I would like to know if everybody agrees on making master === 2.2, in order to keep master as
the development branch (but starting from 2.2) and trying to have "stable" branches 2.1 and 2.2.
This would require a "force push" so I prefer to ask first.

In the future we should really improve the way we work with branches in order to avoid this
situation. 

For the record: we wanted to create a 2.2 branch, compatible both with master (latest development) and 2.1 (previous "stable"). Basically we had to merge 2.1 with master to produce 2.2 ; we decided to do so by creating 2.2 from master and rebasing on 2.1. As a consequence, master and 2.2. have diverged a lot so we need to clean this.

**Comment by IvarsKarpics** [comment]
Can we do that next week at Soleil?

**Comment by MartinSavko** [comment]
Seems like a good session candidate.

**Comment by mguijarr** [comment]
Ok :) Let's see next week.

**Comment by IvarsKarpics** [comment]
2016.03.07. 
Done
