### ISSUE TITLE
Move hardware objects from HardwareRepository/HardwareObjects to HardwareObjects

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareObjects#163]
Hi,

Can we move all hardware objects located in the HardwareRepository/HardwareObjects to HardwareObjects submodule? I know the idea is to have atomic hwobjs in HardwareRepository, but sometimes it is difficult to follow where a hwobj is located.
I think it would be better to have all hwobj in one place (easier maintenance).

**Comment by beteva** [comment]
I guess it is possible, but we should do some cleaning first. Some of the HardwareRepository/HarwareObjects are used at ESRF not only by mxcube and might be incompatible with some of the HO.

**Comment by IvarsKarpics** [comment]
HardwareObjects moved to HardwareRepository/HardwareObjects
