### ISSUE TITLE
File PlateManipulator.py missing ?

### ISSUE THREAD

**Issue by marcus-oscarsson** [mxcube/HardwareObjects#169]
Hi 

Quick question, it seems like there is supposed to be a file called PlateManipulator.py but 
its not present. Did I get this wrong or it is actually missing ?

Regards,
Marcus

**Comment by marcus-oscarsson** [comment]
Sorry I was looking in the wrong place, actually the xml file is wrong. 

PlateManipulator.py is located in the sample_changer directory and not in the HardwareObjects root.

The XML file needs to be updated.

**Comment by IvarsKarpics** [comment]
Hi @marcus-oscarsson 

Yes you are right: xml file needs an update. In my script I added sample_changer to the HardwareObjectsDirs and no problem occurred. The PlateManipulator without exporter channels works as a mockup.

**Comment by marcus-oscarsson** [comment]
Hey !

I see, thanks for the rapid reply. The question was raised when we were trying to help Rasmus at global phasing to install MxCuBE. In anyways, feel free to close this issue when you think its resolved.

Cheers,
Marcus

**Comment by mguijarr** [comment]
Rasmus will soon contribute the fix, then we will close this issue.

**Comment by IvarsKarpics** [comment]
Solved with mxcube/mxcube#149
