### ISSUE TITLE
submodule update broken

### ISSUE THREAD

**Issue by vrey01** [mxcube/HardwareObjects#175]
Last month I submitted pull requests for mxcube and its submodules. At present, the "mxcube" and the "HardwareObjects" pull requests have been accepted.  But the "BlissFramework" and "HardwareRepository" are still pending review and acceptance.  

As a result when doing a "git submodule update" (for a new mxcube installation) the command fails as the BlissFramework commit is pointing to a commit in the BlissFramework that does not exist yet.
The same for the HardwareRepository update.

Could someone review and accept those two pull requests?

This is an issue to pay attention for future pull requests too. I do not know a better way to handle them.

**Comment by mguijarr** [comment]
Hello :) Sorry, with the xmas closure and all the work your PRs remained unnoticed. Now they are merged.
