### ISSUE TITLE
GenericDiffractomer and AbstractCollect

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareObjects#18]
Hi all,
- GenericDiffractometer. So for sure this is not a final version, but an idea what could be a minimal set of function to define API. As a base I used MD2 and MD3. I assume that some things could go out, for example: some states or hardware objects (remove them all and make fully abstract?). As an example you can look at Qt4_DiffractometerMockup.py and EMBL/EMBLMinidiff.py as an implementation. I would encourage people to look at this and slowly start to use it. As an example I can mention GenericSampleChanger that is used as a base for all sample changer and works well. I think diffractometers also should have a generic class and maybe separate directory.
- AbstractCollect is a minimized version of AbstractMulticollect.

**Comment by JieNanMAXIV** [comment]
A quick question regarding the naming conventions. Currently it's a mix of camelCase and underscore. To solve the legacy issue and make the APIs compatible for different sites and mockups, both are used, such as self.startAutoCentring = self.start_automatic_centring, which is a nice quick solution. However it's not implemented in all mockups and hwobj and quite some "bugs" were due to this. 

So it would be nice that at least in the future if we could agree on ONE. Because currently both naming conventions are still showing up in the new codes. What do you say?

**Comment by IvarsKarpics** [comment]
I would wote for the snake style (the one with underscores, for example self.start_automatic_centring). In fact there was before discussion about this. I think we should once define it. Based on PEP https://www.python.org/dev/peps/pep-0008/
-  Function Names: Function names should be lowercase, with words separated by underscores as necessary to improve readability. 
-  Class Names: Class names should normally use the CapWords convention. 
-  Method Names and Instance Variables: Use the function naming rules: lowercase with words separated by underscores as necessary to improve readability. Use one leading underscore only for non-public methods and instance variables.

**Comment by JieNanMAXIV** [comment]
Thanks! We will try to follow the same rules.

**Comment by meguiraun** [comment]
In the v3 development we are using camelCase, although we are not very consistent. In fact we did a pr called Pep8 with camelCase... and we have code with snake_style... bluurrrr

Anyway, if we all agree to follow pep8 it's fine for me, the rules are already defined so it is just a matter of decision... and refactoring, but doable.

**Comment by mguijarr** [comment]
:+1: for PEP8 and snake style for Python code.

**Comment by JieNanMAXIV** [comment]
I have a question on how to copy greenlet in python. 
To solve the legacy issued mentioned above and make the code more compatible, both snake and camelCase are defined as shown below. This works well for methods and dictionaries, but not for greenlet (return of gevent.spawn) as in the case of  self.currentCentringProcedure. Any suggestion of a workaround is appreciated!

**self.currentCentringProcedure = self.current_centring_procedure**
self.start3ClickCentring = self.start_manual_centring
self.startAutoCentring = self.start_automatic_centring
self.imageClicked = self.image_clicked

**Comment by mguijarr** [comment]
You can move all those aliases including the greenlet in `__getattr__`:

```
def __getattr__(self, attr):
    if attr.startswith("__"):
        raise AttributeError(attr)
   else:
        if attr == "currentCentringProcedure":
            return self.current_centring_procedure
       ...
```

It's a bit ugly, but this is ugly with aliases too so... ;)

**Comment by JieNanMAXIV** [comment]
Great, thanks!

**Comment by IvarsKarpics** [comment]
Phases become methods (free to develop new phase, based on a current diffractometer), head types and centring methods as dict.
Clean up MiniDiff.

**Comment by IvarsKarpics** [comment]
Also topic for 2.3 #82
