### ISSUE TITLE
osc_start_cbox in acquisition widget - sense

### ISSUE THREAD

**Issue by lgadea** [mxcube/HardwareObjects#30]
hi all
I create this issue about osc_start_cbox  in acquisition widgets. I would like to know if somebody knows the history and the origin of this option before remove it.
Last march when you came at SOLEIL we discused to leo about it.
 I propose to remove it, because this is meeting  with our expectation in beamline and I noticed this was   a source of confusion for some users. In Soleil we want to remove it and I will submit to the code later. What do you think about this?
Laurent GADEA

**Comment by IvarsKarpics** [comment]
Hi @lgadea ,

At first gui related issues propably should go to BlissFramework or mxcube rep. Anyway...
In our case we would like to use that osc_start_combo because the feature to set a starting osc was not implemented. With this combo when user clicks on it osc_start_ledit is not updated when omega changes and user can define the value.
I would not remove it, but add a property to TaskBrick to hide/show that checkbox and show/hide a label "Oscillation start".
Other option would be to implement changeable osc_start without the checkbox.

cheers,
Ivars

**Comment by hnaalas** [comment]
Dear all

I am not 100% sure I understand the motivations here.

The idea in removing the 'checkbox' is to favour quick change of the oscillation start value, without having to click on the checkbox itself to activate this field. I do not really see the advantage nor motivation of having a checkbox that only allows entering a value in the oscillation start box. Could you please comment on this? What does it add exactly?

Cheers, leo

> On 13 Apr 2016, at 15:10, Ivars Karpics notifications@github.com wrote:
> 
> Hi @lgadea ,
> 
> At first gui related issues propably should go to BlissFramework or mxcube rep. Anyway...
> In our case we would like to use that osc_start_combo because the feature to set a starting osc was not implemented. With this combo when user clicks on it osc_start_ledit is not updated when omega changes and user can define the value.
> I would not remove it, but add a property to TaskBrick to hide/show that checkbox and show/hide a label "Oscillation start".
> Other option would be to implement changeable osc_start without the checkbox.
> 
> cheers,
> Ivars
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub

## 

## Leonard Chavas

Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex

## France

Phone:  +33 169 359 746
Mobile: +33 644 321 614

## E-mail: leonard.chavas@synchrotron-soleil.fr

**Comment by IvarsKarpics** [comment]
Hi Leo @hnaalas 

The idea of checkbox is to "freeze" osc_start value and allow to edit it. In fact, if an user changes any parameter (energy, transmission, osc_start) and the value of this parameter is changed during the editing, then the typed value will disappear and will be overwritten by current value. Here I am talking about the situation when sample is selected. When a collection is added to queue, of course parameters are not updated and user freely can edit it.
I dont know what is here best, but it is not difficult to implement both behaviors (with and without checkbox). I will try to implement it

**Comment by hnaalas** [comment]
Hi Ivars

thanks a lot for your quick feedback.

I completely agree with you willing to fix the original value of the starting angle until it is edited, but I don't really see the difference between this value and others... In this logic of checkbox-fixing generally used parameters, you will have checkboxes everywhere. It is only my own feeling, but it is not really _dangerous_ to have the box accessible at all time, if for any mounted sample it is reset to a default value, which is usually (if not always) 0.00 after the mounting procedure. As there is absolutely no relationship between samples in terms of mounted angle, to define this starting angle different than 0.00 is for me nonsense. Now, from one dataset to another on the same sample, I do understand the different possibilities: keeping to the current angle or setting it back to 0.00. I see advantages in both cases; I believe that the second option is currently the one accepted, which makes more sense to me, at least statistically.

Cheers, leo

> On 15 Apr 2016, at 08:41, Ivars Karpics notifications@github.com wrote:
> 
> Hi Leo @hnaalas
> 
> The idea of checkbox is to "freeze" osc_start value and allow to edit it. In fact, if an user changes any parameter (energy, transmission, osc_start) and the value of this parameter is changed during the editing, then the typed value will disappear and will be overwritten by current value. Here I am talking about the situation when sample is selected. When a collection is added to queue, of course parameters are not updated and user freely can edit it.
> I dont know what is here best, but it is not difficult to implement both behaviors (with and without checkbox). I will try to implement it
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

## 

## Leonard Chavas

Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex

## France

Phone:  +33 169 359 746
Mobile: +33 644 321 614

## E-mail: leonard.chavas@synchrotron-soleil.fr

**Comment by hnaalas** [comment]
Hi Ivars

just to come back on this: did you guy come up with some new features / decisions on this?

Cheers, leo

> On 16 Apr 2016, at 02:22, CHAVAS Leonard leonard.chavas@synchrotron-soleil.fr wrote:
> 
> Hi Ivars
> 
> thanks a lot for your quick feedback.
> 
> I completely agree with you willing to fix the original value of the starting angle until it is edited, but I don't really see the difference between this value and others... In this logic of checkbox-fixing generally used parameters, you will have checkboxes everywhere. It is only my own feeling, but it is not really _dangerous_ to have the box accessible at all time, if for any mounted sample it is reset to a default value, which is usually (if not always) 0.00 after the mounting procedure. As there is absolutely no relationship between samples in terms of mounted angle, to define this starting angle different than 0.00 is for me nonsense. Now, from one dataset to another on the same sample, I do understand the different possibilities: keeping to the current angle or setting it back to 0.00. I see advantages in both cases; I believe that the second option is currently the one accepted, which makes more sense to me, at least statistically.
> 
> Cheers, leo
> 
> > On 15 Apr 2016, at 08:41, Ivars Karpics notifications@github.com wrote:
> > 
> > Hi Leo @hnaalas
> > 
> > The idea of checkbox is to "freeze" osc_start value and allow to edit it. In fact, if an user changes any parameter (energy, transmission, osc_start) and the value of this parameter is changed during the editing, then the typed value will disappear and will be overwritten by current value. Here I am talking about the situation when sample is selected. When a collection is added to queue, of course parameters are not updated and user freely can edit it.
> > I dont know what is here best, but it is not difficult to implement both behaviors (with and without checkbox). I will try to implement it
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> 
> ## 
> 
> ## Leonard Chavas
> 
> Synchrotron SOLEIL
> Proxima-I
> L'Orme des Merisiers
> Saint-Aubin - BP 48
> 91192 Gif-sur-Yvette Cedex
> 
> ## France
> 
> Phone:  +33 169 359 746
> Mobile: +33 644 321 614
> 
> ## E-mail: leonard.chavas@synchrotron-soleil.fr

## 

## Leonard Chavas

Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex

## France

Phone:  +33 169 359 746
Mobile: +33 644 321 614

## E-mail: leonard.chavas@synchrotron-soleil.fr

**Comment by IvarsKarpics** [comment]
Hi,

I made a solution for this: a property that enables/disables the checkbox. I will push it to the git asap.

**Comment by IvarsKarpics** [comment]
Hi @hnaalas 

I pushed changes to the master. See:
https://github.com/mxcube/mxcube/commit/9ce81b2c8d03fc0f2c47facbd24956c6f1e2bddf

cheers,
Ivars

**Comment by lgadea** [comment]
hi ivarsthx a lottomorrow i pull it  and test it on PX1
 Mr Gadea Laurent
11 allée du Parc de la Bièvre
94240 L'Hay Les Roses
01 49 73 29 85
06 20 85 17 44

```
Le Lundi 25 avril 2016 15h01, Ivars Karpics <notifications@github.com> a écrit :
```

 Hi @hnaalas I pushed changes to the master. See:
mxcube/mxcube@9ce81b2cheers,
Ivars—

**Comment by hnaalas** [comment]
Hi Ivars

great, thank you!

Cheers, leo

> On 25 Apr 2016, at 08:58, Ivars Karpics notifications@github.com wrote:
> 
> Hi,
> 
> I made a solution for this: a property that enables/disables the checkbox. I will push it to the git asap.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

## 

## Leonard Chavas

Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex

## France

Phone:  +33 169 359 746
Mobile: +33 644 321 614

## E-mail: leonard.chavas@synchrotron-soleil.fr

**Comment by hnaalas** [comment]
Hi Ivars

thanks a lot for all this! We'll have it implemented at SOLEIL and let you know if anything 'wrong' happens.

Cheers, leo

> On 25 Apr 2016, at 15:01, Ivars Karpics notifications@github.com wrote:
> 
> Hi @hnaalas
> 
> I pushed changes to the master. See:
> mxcube/mxcube@9ce81b2
> 
> cheers,
> Ivars
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

## 

## Leonard Chavas

Synchrotron SOLEIL
Proxima-I
L'Orme des Merisiers
Saint-Aubin - BP 48
91192 Gif-sur-Yvette Cedex

## France

Phone:  +33 169 359 746
Mobile: +33 644 321 614

## E-mail: leonard.chavas@synchrotron-soleil.fr

**Comment by IvarsKarpics** [comment]
I will close this issue. If there is any gui related bug then report it in mxcube or BlissFramework issues.
