### ISSUE TITLE
DiffractometerMockup

### ISSUE THREAD

**Issue by IvarsKarpics** [mxcube/HardwareObjects#81]
Hi all,

I see two versions of mockup diffractometers: DiffractometerMockup and Qt4_DiffractometerMockup.py.
The first one is old version with qub and it is not subclassed from GenericDiffractometer.
Would it be fine to remove prefix Qt4 from Qt4_DiffractometerMockup and use it as the main mockup?

**Comment by mguijarr** [comment]
`DiffractometerMockup` is used by MXCuBE 3 to have a simulated diffractometer.

So, I propose to insert a deprecation warning in `DiffractometerMockup.py` in `2.2` branch to indicate it will be deprecated in  `2.3`, and we can already rename `Qt4_DiffractometerMockup.py`  to `DiffractometerMockup.py` in `master` (as it is the base for `2.3`).

By the way... I created an issue for the new `2.3` branch, see #82

**Comment by IvarsKarpics** [comment]
Hi @mguijarr 

Thanks for a fast replay and good suggestions. I think we should use more active deprecation warnings. 
Yes, a list of TODOs for the 2.3 branch is a good idea. I will switch to issue #82

**Comment by IvarsKarpics** [comment]
All discussions about 2.3 should be in #82. I will close this.
