### ISSUE TITLE
CenteringMath / Diffractometer documentation

### ISSUE THREAD

**Issue by sallazda** [mxcube/HardwareObjects#93]
Hello,
I tried to configure the CenteringMath HwO but I lack of information about the axis coordinate system used. Therefore, I need documentation about this to move forward.
Thank you
Best regards

**Comment by IvarsKarpics** [comment]
Hi  @sallazda 

Here is a short description of the math behind the centering procedure.
[centering.pdf](https://github.com/mxcube/HardwareObjects/files/432077/centering.pdf)
Here are some configuration examples:
- MD2 horizontal direction of the spindle axis: https://github.com/mxcube/mxcube/blob/master/ExampleFiles/HardwareObjects.xml/embl_hh_p13/centring-math.xml
- MD3 vertical direction of the spindle axis:
  https://github.com/mxcube/mxcube/blob/master/ExampleFiles/HardwareObjects.xml/embl_hh_p14/centring-math.xml

Hope it helps to understand it better

**Comment by IvarsKarpics** [comment]
In the last meeting Jie from MaxIV had a nice presentation about MD3 integration in mxcube:
http://mxcube.github.io/mxcube/doc/meetings_2016_EMBL/integration_of_MD3.pdf

**Comment by sallazda** [comment]
Thank you very much
I was able to configure the software successfully with yours documents
